### ISSUE TITLE
Post credentials on form_login

### ISSUE THREAD

**Issue by raziel057** [slashfan/LexikJWTAuthenticationBundleSandbox#2]
Is it really secure to post the credentials (in clear) to the form_login? If a system listen the data between the client and the server at authentication (man in the middle), it can get the credentials. No?

What do you think about that? Do you consider this solution safe because you access the API through SSL connections (https) ?

**Comment by slashfan** [comment]
Keep in mind that this repository is only a usage demonstration sandbox.

About your concern, this is not different than a regular html form login. If it is not correctly protected, it will be vulnerable to a man in the middle attack. In a production environment, you must allow only SSL/HTTPS communication. This recommandation also applies to token exchanges.

**Comment by raziel057** [comment]
Thanks for your reply and for your demonstration sandbox.
